//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketOtomasyonEntities : DbContext
    {
        public MarketOtomasyonEntities()
            : base("name=MarketOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_ADVANCEPAYMENT> tbl_ADVANCEPAYMENT { get; set; }
        public virtual DbSet<tbl_CUSTOMER> tbl_CUSTOMER { get; set; }
        public virtual DbSet<tbl_CUSTOMERDEBTPAYMENT> tbl_CUSTOMERDEBTPAYMENT { get; set; }
        public virtual DbSet<tbl_ONCREDIT> tbl_ONCREDIT { get; set; }
        public virtual DbSet<tbl_PRODUCT> tbl_PRODUCT { get; set; }
        public virtual DbSet<tbl_SELL2> tbl_SELL2 { get; set; }
        public virtual DbSet<tbl_SELLER> tbl_SELLER { get; set; }
        public virtual DbSet<tbl_SHOPPINGCART> tbl_SHOPPINGCART { get; set; }
        public virtual DbSet<tbl_SHOPPINGPRODUCTID> tbl_SHOPPINGPRODUCTID { get; set; }
        public virtual DbSet<tbl_SUPPDEBTPAYMENT> tbl_SUPPDEBTPAYMENT { get; set; }
        public virtual DbSet<tbl_SUPPLIER> tbl_SUPPLIER { get; set; }
        public virtual DbSet<tbl_WAYBILL> tbl_WAYBILL { get; set; }
    }
}
