//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ONCREDIT
    {
        public int creditID { get; set; }
        public Nullable<int> sellID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> shoppingCartID { get; set; }
    
        public virtual tbl_CUSTOMER tbl_CUSTOMER { get; set; }
        public virtual tbl_SELL2 tbl_SELL2 { get; set; }
        public virtual tbl_SELL2 tbl_SELL21 { get; set; }
        public virtual tbl_SHOPPINGCART tbl_SHOPPINGCART { get; set; }
    }
}
