//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SELL2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SELL2()
        {
            this.tbl_ADVANCEPAYMENT = new HashSet<tbl_ADVANCEPAYMENT>();
            this.tbl_ONCREDIT = new HashSet<tbl_ONCREDIT>();
            this.tbl_ONCREDIT1 = new HashSet<tbl_ONCREDIT>();
        }
    
        public int sellID { get; set; }
        public string definition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ADVANCEPAYMENT> tbl_ADVANCEPAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ONCREDIT> tbl_ONCREDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ONCREDIT> tbl_ONCREDIT1 { get; set; }
    }
}
