//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHOPPINGCART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SHOPPINGCART()
        {
            this.tbl_ONCREDIT = new HashSet<tbl_ONCREDIT>();
            this.tbl_SHOPPINGPRODUCTID = new HashSet<tbl_SHOPPINGPRODUCTID>();
        }
    
        public int shoppingCartID { get; set; }
        public Nullable<int> sellID { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ONCREDIT> tbl_ONCREDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHOPPINGPRODUCTID> tbl_SHOPPINGPRODUCTID { get; set; }
    }
}
