//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CUSTOMERDEBTPAYMENT
    {
        public int customerDebtPayment { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> payment { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual tbl_CUSTOMER tbl_CUSTOMER { get; set; }
    }
}
