//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CUSTOMER()
        {
            this.tbl_CUSTOMERDEBTPAYMENT = new HashSet<tbl_CUSTOMERDEBTPAYMENT>();
            this.tbl_ONCREDIT = new HashSet<tbl_ONCREDIT>();
        }
    
        public int customerID { get; set; }
        public string customerName { get; set; }
        public Nullable<double> customerDebt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CUSTOMERDEBTPAYMENT> tbl_CUSTOMERDEBTPAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ONCREDIT> tbl_ONCREDIT { get; set; }
    }
}
