//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHOPPINGPRODUCTID
    {
        public int shoppingCartProductID { get; set; }
        public Nullable<int> shoppingCartID { get; set; }
        public Nullable<int> productBarcode { get; set; }
        public Nullable<double> sellQuantity { get; set; }
        public Nullable<double> labelPrice { get; set; }
    
        public virtual tbl_SHOPPINGCART tbl_SHOPPINGCART { get; set; }
    }
}
